### ISSUE TITLE
Migrate away from KEYCLOAK_* to KC_*

### ISSUE THREAD

**Issue by jack1902** [bitnami/bitnami-docker-keycloak#72] opened 2022-05-26 13:05 UTC
### Name and Version

bitnami/keycloak

### What is the problem this feature will solve?

Currently, many `KEYCLOAK_` env-vars exist within the image, but not all of them directly map to something meaningful inside the Quarkus distribution of keycloak. It would be better to use `KC_*` where appropriate.

For example, I have raised two PRs to address this but kept `KEYCLOAK_` as an option for now.

PRs:

https://github.com/bitnami/bitnami-docker-keycloak/pull/70
https://github.com/bitnami/bitnami-docker-keycloak/pull/71

### What is the feature you are proposing to solve the problem?

Remove any dud `KEYCLOAK_*` and replace them with their correct alternatives of `KC_*` according to the settings page of the Quarkus distribution.

https://www.keycloak.org/server/all-config

With this type of change being implemented, then have a release note in the README about migrating away from old to new so that future images are cleaner and simpler

### What alternatives have you considered?

Continue to raise PRs to map old to new which will eventually get out of hand, as there will be many different permutations of what inputs could be given which increases complexity.

**Comment by marrws** [comment] 2022-05-26 17:20
> (...)
> PRs:
> 
> #70 #71
> ### What is the feature you are proposing to solve the problem?
> 
> Remove any dud `KEYCLOAK_*` and replace them with their correct alternatives of `KC_*` according to the settings page of the Quarkus distribution.
> (...)

#70 is a duplicate of the already merged #65, my guess is that #65 was overwritten by #68 (your edge/no-tls PR) while merging

**Comment by jack1902** [comment] 2022-05-26 21:52
Fair enough, I do believe we should move to KC over KEYCLOAK though

**Comment by rafariossaa** [comment] 2022-05-27 08:07
Hi,
  I am not very sure of this issue. 
  You could add the `KC_xxx` environment variables that you need when running the contianer. The `KEYCLOACK_xxx` ones are used to create the configuration file instead.

**Comment by jack1902** [comment] 2022-05-27 08:46
Some of the previous `KEYCLOAK_` env-vars actually served a purpose directly to the app itself, but have since been renamed to new env-vars within keycloak.

For example `KEYCLOAK_FRONTEND_URL` is entirely meaningless but exists in the file. It should be `KC_HOSTNAME`. I feel every env-var in the file should serve a purpose or not exist at all. Maintaining old and new env-vars within the file just makes it bloated and doesn't really add much as you can migrate people onto the new ones.

Whilst I can pass any env-var in to the container, it is confusing to see env-vars exist within a script which don't have any relevance to the underlying app anymore

**Comment by rafariossaa** [comment] 2022-05-30 07:13
Hi,
  I am opening an internal task to review the env vars and take the actions needed.
  This will take a while and I can not provide an ETA, but we will come back as soon as we have news.
  Meanwhile maybe you want to consider sending a PR to fix this, we will be glad to review and merge it.

**Closed** 2022-07-04 08:07 UTC

**Comment by jack1902** [comment] 2022-07-04 08:12
In terms of the initialisation logic, i agree, far too much is being done in the scripts which really should be left down to the app. One of the initial issue many ran into was because of logic added to the script which had it been passed to keycloak directly would have been fine.

In terms of the config file and env-vars, i wonder if there would be merit in just passing "keycloak-env-vars" as a object straight to keycloak and the config file without parsing it (any bad env-vars will be ignored by keycloak itself and wrong combinations shoulds surely cause keycloak to blow up itself with its own validation). Doing this removes the maintenance burden of the script as keycloak iterates forward and backwards compatibility is constantly attempted to be maintained (hence the whole KC_ piece as keycloak no longer cares for KEYCLOAK_ env-vars.)
